openapi: 3.0.1
info:
  title: Merchant API
  version: 1.4.0
paths:
  /mapi/feeQuote:
    get:
      tags:
        - Mapi
      summary: Get a fee quote.
      description: >-
        This endpoint returns a JSONEnvelope with a payload that contains the
        fees charged by a specific BSV miner.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/FeeQuoteViewModelGet'
            application/json:
              schema:
                $ref: '#/components/schemas/FeeQuoteViewModelGet'
            text/json:
              schema:
                $ref: '#/components/schemas/FeeQuoteViewModelGet'
  /mapi/policyQuote:
    get:
      tags:
        - Mapi
      summary: Get a policy quote.
      description: >-
        This endpoint returns a JSONEnvelope with a PolicyQuote payload that
        contains the fees charged by a specific BSV miner and set policies.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PolicyQuoteViewModelGet'
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyQuoteViewModelGet'
            text/json:
              schema:
                $ref: '#/components/schemas/PolicyQuoteViewModelGet'
  /mapi/tx/{id}:
    get:
      tags:
        - Mapi
      summary: Query transaction status.
      description: >-
        This endpoint is used to check the current status of a previously
        submitted transaction.
      parameters:
        - name: id
          in: path
          description: The transaction ID (32 byte hash) hex string
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/QueryTransactionStatusResponseViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/QueryTransactionStatusResponseViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/QueryTransactionStatusResponseViewModel'
  /mapi/tx:
    post:
      tags:
        - Mapi
      summary: Submit a transaction.
      description: >-
        This endpoint is used to send a raw transaction to a miner for inclusion
        in the next block that the miner creates.
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitTransactionViewModel'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResponseViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResponseViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResponseViewModel'
  /mapi/txs:
    post:
      tags:
        - Mapi
      summary: Submit multiple transactions.
      description: >-
        This endpoint is used to send multiple raw transactions to a miner for
        inclusion in the next block that the miner creates.
      parameters:
        - name: defaultCallbackUrl
          in: query
          description: >-
            Default double spend and merkle proof notification callback
            endpoint.
          schema:
            type: string
        - name: defaultCallbackToken
          in: query
          description: Default access token for notification callback endpoint.
          schema:
            type: string
        - name: defaultCallbackEncryption
          in: query
          schema:
            type: string
        - name: defaultMerkleProof
          in: query
          description: Default merkle proof requirement.
          schema:
            type: boolean
        - name: defaultMerkleFormat
          in: query
          schema:
            type: string
        - name: defaultDsCheck
          in: query
          description: Default double spend notification request.
          schema:
            type: boolean
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SubmitTransactionViewModel'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResponseViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResponseViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/SubmitTransactionResponseViewModel'
components:
  schemas:
    CallbackViewModelGet:
      type: object
      properties:
        ipAddress:
          type: string
          nullable: true
      additionalProperties: false
    FeeAmountViewModelGet:
      type: object
      properties:
        satoshis:
          type: integer
          format: int32
        bytes:
          type: integer
          format: int32
      additionalProperties: false
    FeeQuoteViewModelGet:
      type: object
      properties:
        apiVersion:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
        expiryTime:
          type: string
          format: date-time
        minerId:
          type: string
          nullable: true
        currentHighestBlockHash:
          type: string
          nullable: true
        currentHighestBlockHeight:
          type: integer
          format: int64
        fees:
          type: array
          items:
            $ref: '#/components/schemas/FeeViewModelGet'
          nullable: true
        callbacks:
          type: array
          items:
            $ref: '#/components/schemas/CallbackViewModelGet'
          nullable: true
      additionalProperties: false
    FeeViewModelGet:
      type: object
      properties:
        feeType:
          type: string
          nullable: true
        miningFee:
          $ref: '#/components/schemas/FeeAmountViewModelGet'
        relayFee:
          $ref: '#/components/schemas/FeeAmountViewModelGet'
      additionalProperties: false
    PolicyQuoteViewModelGet:
      type: object
      properties:
        apiVersion:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
        expiryTime:
          type: string
          format: date-time
        minerId:
          type: string
          nullable: true
        currentHighestBlockHash:
          type: string
          nullable: true
        currentHighestBlockHeight:
          type: integer
          format: int64
        fees:
          type: array
          items:
            $ref: '#/components/schemas/FeeViewModelGet'
          nullable: true
        callbacks:
          type: array
          items:
            $ref: '#/components/schemas/CallbackViewModelGet'
          nullable: true
        policies:
          type: object
          additionalProperties: {}
          nullable: true
      additionalProperties: false
    QueryTransactionStatusResponseViewModel:
      type: object
      properties:
        apiVersion:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
        txid:
          type: string
          nullable: true
        returnResult:
          type: string
          nullable: true
        resultDescription:
          type: string
          nullable: true
        blockHash:
          type: string
          nullable: true
        blockHeight:
          type: integer
          format: int64
          nullable: true
        confirmations:
          type: integer
          format: int64
          nullable: true
        minerId:
          type: string
          nullable: true
        txSecondMempoolExpiry:
          type: integer
          format: int32
      additionalProperties: false
    SubmitTransactionConflictedTxResponseViewModel:
      type: object
      properties:
        txid:
          type: string
          nullable: true
        size:
          type: integer
          format: int64
        hex:
          type: string
          nullable: true
      additionalProperties: false
    SubmitTransactionResponseViewModel:
      type: object
      properties:
        apiVersion:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
        txid:
          type: string
          nullable: true
        returnResult:
          type: string
          nullable: true
        resultDescription:
          type: string
          nullable: true
        minerId:
          type: string
          nullable: true
        currentHighestBlockHash:
          type: string
          nullable: true
        currentHighestBlockHeight:
          type: integer
          format: int64
        txSecondMempoolExpiry:
          type: integer
          format: int64
        conflictedWith:
          type: array
          items:
            $ref: >-
              #/components/schemas/SubmitTransactionConflictedTxResponseViewModel
          nullable: true
      additionalProperties: false
    SubmitTransactionViewModel:
      type: object
      properties:
        rawTx:
          type: string
          nullable: true
        callbackUrl:
          type: string
          nullable: true
        callbackToken:
          type: string
          nullable: true
        callbackEncryption:
          type: string
          nullable: true
        merkleProof:
          type: boolean
          nullable: true
        merkleFormat:
          type: string
          nullable: true
        dsCheck:
          type: boolean
          nullable: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: >-
        Please enter JWT with Bearer needed to access MAPI into field.
        Authorization: Bearer JWT
      name: Authorization
      in: header
    Api-Key:
      type: apiKey
      description: >-
        Please enter API key needed to access admin endpoints into field.
        Api-Key: My_API_Key
      name: Api-Key
      in: header
security:
  - Bearer: []
  - Api-Key: []
