global:
  scrape_interval: 1m
  scrape_timeout: 1m

scrape_configs:

  - job_name: mapi_metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true

    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:5051'