version: '3.7'

services:

  merchant-gateway-database:    

  merchant-gateway-api:    
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9080:9090
    volumes:
      - ../prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  mapi-volume:  
  prometheus-data:
  grafana-data:
  
networks:
  mapi-network: